### ISSUE TITLE
Where to get the files

### ISSUE THREAD

**Issue by ziyadsaeed** [gersolar/linketurbidity#9]
The documentation doesn't mention where to get the  NOAA CLASS netcdf files.

**Comment by ecolell** [comment]
Hi!,
Thanks, we append the link of the site into the README but it is not the subject of this libraries to download the files; but to help to resolve your specific quest: you should make an account into the [NOAA CLASS site](http://www.nsof.class.noaa.gov/saa/products/welcome), then check the [noaaclass](https://github.com/gersolar/noaaclass) and [goesdownloader](https://github.com/gersolar/goesdownloader) libraries.

Ask about the download of images inside the **goesdownloader** or **noaaclass** project and I'll try to help you in that place.
